version: '3.8'

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp_dev_container
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_dev
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: local
    volumes:
      - wp_dev_data:/var/www/html
    restart: always
    mem_limit: 4g
    cpus: 2.0

  db:
    image: mysql:8.0
    container_name: wp_dev_db
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: wp_dev
      MYSQL_USER: sergio
      MYSQL_PASSWORD: mercatello
    #ports:
    #  - "3306:3306" # phpMyAdmin sarà accessibile sulla porta 8080  
    volumes:
      - wp_mysql_dev_data:/var/lib/mysql
    restart: always
    mem_limit: 3g
    cpus: 2.0

  nginx:
    image: nginx:alpine
    container_name: wp_dev_nginx
    depends_on:
      - wordpress
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d # Configurazione Nginx
      - wp_dev_data:/var/www/html # Collegamento ai file di WordPress
    ports:
      - "8001:80" # Nginx usa la porta 80 dell'host
    restart: always
    mem_limit: 1g
    cpus: 1.0


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp_dev_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: local
    ports:
      - "8081:80" # phpMyAdmin sarà accessibile sulla porta 8080
    depends_on:
      - db
    restart: always  

volumes:
  wp_dev_data:
  wp_mysql_dev_data:

